name: Run Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Logica Ejecucion Pruebas
      run: |
        if [[ ${{ github.event_name }} == 'pull_request' ]]; then
          echo "La ejecución fue a través de un pull request, ejecutando pruebas nuevas"
          mvn -B package --file pom.xml
        else
          echo "La ejecución no fue por un pull request, ejecutando comando 2..."
          mvn test -DsuiteXmlFile=$GITHUB_WORKSPACE/tests/testng.xml
        fi
      continue-on-error: true

    - name: Get Report
      run: | 
        latest_report=$(ls -t report/*.html | head -n 1)
        cat $latest_report > AutomationReport.html

    - name: Publish Automation Report
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Automation Report HTML
        path: AutomationReport.html

    - name: Copy testng.xml
      run: |
        mkdir $GITHUB_WORKSPACE/tests
        cp testng.xml  $GITHUB_WORKSPACE/tests/
        cp testng.dtd  $GITHUB_WORKSPACE/tests/
        echo $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE/tests/
      continue-on-error: true
