name: Run Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Copy testng.xml
      run: |
        mkdir $GITHUB_WORKSPACE/tests
        cp testng.xml  $GITHUB_WORKSPACE/tests/
      continue-on-error: true
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml  
      continue-on-error: true

    - name: Get Report
      run: | 
        latest_report=$(ls -t report/*.html | head -n 1)
        cat $latest_report > AutomationReport.html

    - name: Publish Automation Report
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Automation Report HTML
        path: AutomationReport.html
